### ISSUE TITLE
Please submit mongodb collectd plugin changes upstream

### ISSUE THREAD

**Issue by averi** [Stackdriver/collectd#145]
Stackdriver team,

The mongodb collectd plugin is currently not being shipped in EPEL and I believe that's related to the fact the "official" module hasn't seen an update since 2012 (according to [1]). According to [2] a fixed and confirmed working plugin (based on [1]) has been developed but the contributions were never submitted back upstream to be then consumed by the major Linux distributions out there. Would it be possible for this to happen in order for collectd to finally have an officially supported mongodb plugin?

Thanks!

[1] https://collectd.org/wiki/index.php/Plugin:MongoDB
[2] https://cloud.google.com/monitoring/agent/plugins/mongodb

**Comment by jkohen** [comment]
@octo we'd be happy to contribute this plugin, but you're the original author. What would you suggest?

**Comment by igorpeshansky** [comment]
Just a bit of context: the plugin relies on `libmongoc`, which isn't present on older, but still current, systems (e.g., CentOS 6/7). We have fixed the build to work with system `libmongoc` as well, but have maintained a vendored version of `libmongoc` for such older systems. @octo, how important would it be for the plugin to build on, e.g., CentOS 6/7?

**Comment by jkohen** [comment]
Offline we reached agreement with @tokkee to merge this back. I'm not sure when we'll get to this, but we're happy to take contributions @averi

**Comment by jkohen** [comment]
@qingling128 please triage.

**Comment by qingling128** [comment]
We will not be merging this upstream, because `mongodb` plugin integration with Stackdriver has been deprecated for Collectd. Instead, the guide below provides the steps to transition these integrations to BindPlane, a solution provided by Stackdriver partner, Blue Medora. 

https://cloud.google.com/stackdriver/docs/deprecations/third-party-apps.

**Comment by qingling128** [comment]
In fact, I just noticed we reached agreement offline to merge this as mentioned above (https://github.com/Stackdriver/collectd/issues/145#issuecomment-531937178). Will sync with @jkohen to get more context before closing this.

**Comment by qingling128** [comment]
@averi - Sorry for the confusion. Just sync'ed with @jkohen and understood the context better.

So we've gotten green lights from the Mongodb collectd plugin's author side (@octo @tokkee) that it's fine to contribute this plugin upstream as men. Looking at our team's roadmap from Stackdriver side, Mongodb integration has been moved to another partner and no longer something we would support with Collectd (as mentioned in https://github.com/Stackdriver/collectd/issues/145#issuecomment-537747499). The priority would be very low compared to other tasks we need to complete. Feel free to take it and contribute to the upstream project though. Our license also permits so.

**Comment by igorpeshansky** [comment]
@averi, if you do so, you might want to take the plugin code from the [stackdriver-agent-5.8.1 branch](https://github.com/Stackdriver/collectd/tree/stackdriver-agent-5.8.1) — it's closer to the upstream master.

**Comment by averi** [comment]
@qingling128, my time won't permit to handle this myself unfortunately, the point here was having a patch sent to upstream collectd so that we can go ahead and have the mongodb plugin added to the EPEL package and have the wider community take benefit from it.

**Comment by qingling128** [comment]
Understood. For now, this would not be on our prioritized item list (at least in the near term). If anything changes in the future, we'll update this issue.
