### ISSUE TITLE
set monitored resource in stackdriver agent

### ISSUE THREAD

**Issue by grumvalski** [Stackdriver/collectd#146]
In our k8s we are using stackdriver-agent in side containers to collect metrics from applications and send them as custom metrics to stackdriver through write_gcm.
It looks like in write_gcm the monitored resource is hardcoded to 'gce_instance', making not possible to have different metrics, one per pod, in case several replicas of a pod are running on the node.
*   Version of collectd:5.5.2
*   Operating system / distribution: CentOS Linux release 7.5/GKE

## Expected behavior

Possible to set the monitored resource type.

## Actual behavior

Monitored resource is hardcoded to 'gce_instance'

## Steps to reproduce
Send any custom metric using stackdriver-agent and write_gcm plugin.

**Comment by jkohen** [comment]
Thanks for the suggestion. Our recommended monitoring solution for GKE is described on this page: https://cloud.google.com/monitoring/kubernetes-engine/prometheus

We also provide an alternative: https://cloud.google.com/stackdriver/docs/deprecations/third-party-apps#blue_medora_support_for_deprecated_integrations
