### ISSUE TITLE
Support for Debian 10 buster?

### ISSUE THREAD

**Issue by Carrotman42** [Stackdriver/collectd#155]
Please let me know if this should be asked elsewhere.

I tried to install the monitoring agent based on instructions from the [official docs](https://cloud.google.com/monitoring/agent/install-agent) but it turns out my OS is not supported; this is correctly reflected on the [list of supported OSes](https://cloud.google.com/monitoring/agent/#supported_operating_systems), where `Debian 9 "Stretch"` is listed but no later versions are available.

Is there known incompatibility with `Debian 10 "buster"`, or has an official release just not yet been created?

**Comment by igorpeshansky** [comment]
This is being actively worked on. As a heads-up, we will very likely not release Debian 10 off the `stackdriver-agent-5.5.2` branch, but rather from a newer codebase, so it'll be in a new major agent version, which will remove some of the third-party integrations (see the [agent deprecation policy](https://cloud.google.com/stackdriver/docs/agent-deprecation-policy)).

**Comment by Carrotman42** [comment]
I don't quite mind which codebase will be used as long as it will export the extra metrics promised by various docs :)

**Comment by igorpeshansky** [comment]
The next major release (6.0.0) *will* deprecate a number of third-party integrations, as indicated in https://cloud.google.com/monitoring/agent/plugins/, which is why I mentioned it.

**Comment by Carrotman42** [comment]
Thanks for clarifying. In my case my third-party application isn't supported, so I'm just looking for the general OS-level stats.

**Comment by mercuriete** [comment]
I just installed a debian 10 VM on google cloud platform and I get this:
```
 sudo bash install-monitoring-agent.sh
==============================================================================
Starting installation of stackdriver-agent
==============================================================================

Installing agent for Debian or Ubuntu.
OK
Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:2 http://deb.debian.org/debian buster InRelease                                              
Hit:3 http://deb.debian.org/debian buster-updates InRelease                                      
Hit:4 http://deb.debian.org/debian buster-backports InRelease                                    
Hit:5 https://download.docker.com/linux/debian buster InRelease                                  
Hit:6 http://packages.cloud.google.com/apt cloud-sdk-buster InRelease      
Hit:7 http://packages.cloud.google.com/apt google-cloud-packages-archive-keyring-buster InRelease
Hit:8 http://packages.cloud.google.com/apt google-cloud-logging-wheezy InRelease
Hit:9 http://packages.cloud.google.com/apt google-cloud-monitoring-buster InRelease
Hit:10 http://packages.cloud.google.com/apt google-compute-engine-buster-stable InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package stackdriver-agent
dpkg-query: no packages found matching stackdriver-agent
Failed to restart stackdriver-agent.service: Unit stackdriver-agent.service not found.

==============================================================================
Errors occurred while installing stackdriver-agent-. See the log snippet
above or run:
  sudo service stackdriver-agent status

Please consult the documentation for troubleshooting advice:
  https://cloud.google.com/monitoring/agent

You can monitor the monitoring agent's logfile at:
  /var/log/syslog
==============================================================================
```

There are any other way to monitor RAM usage on GCP?

@Carrotman42 Did you manage to workaround the problem?
I need some basic stats like RAM and disk usage like you.

EDIT:
this url is empty.
https://packages.cloud.google.com/apt/dists/google-cloud-monitoring-buster/main/binary-amd64/Packages

but this is not empty:
https://packages.cloud.google.com/apt/dists/google-cloud-monitoring-buster-unstable/main/binary-amd64/Packages

EDIT2:
for people that hit this bug like me:

change this line on /etc/apt/sources.list.d/google-cloud-monitoring.list
from:
```deb http://packages.cloud.google.com/apt google-cloud-monitoring-buster main```
to
```deb http://packages.cloud.google.com/apt google-cloud-monitoring-buster-unstable main```
then:
```
sudo apt-get update
sudo apt-get install stackdriver-agent
sudo systemctl restart stackdriver-agent.service
```

hope this help

**Comment by igorpeshansky** [comment]
Careful with `unstable`. As the name implies, the package in that repo may be completely broken at any point, and is not guaranteed to work. Further, unstable does not keep older packages, so you're always getting the latest push, and one install unstable may not be the same as another. Use at your own risk.
We plan to release a stable 6.0.0 version with support for Debian 10 before the end of this quarter.

**Comment by mercuriete** [comment]
@igorpeshansky 
Thanks for the clarification. I'll wait for stable in my production environments.

**Comment by qingling128** [comment]
Debian 10 is now officially supported: https://cloud.google.com/monitoring/agent/install-agent#agent-install-debian.
