### ISSUE TITLE
Arch install fail: "This version of libsensors is not supported yet. Please report this." lm_sensors = 3.6.0

### ISSUE THREAD

**Issue by crunk1** [Stackdriver/collectd#195]
*   Version of collectd: 6.1.1
*   Operating system / distribution: archlinux 5.10.16-arch1-1

## Expected behavior
`yay -S stackdriver-collectd` should install

## Actual behavior
Build/install fails with `src/sensors.c:165:2: error: #error "This version of libsensors is not supported yet. Please report this " "as bug."`

Sensors version:
```
> yay -Q lm_sensors          
lm_sensors 1:3.6.0.r41.g31d1f125-1
```

## Steps to reproduce
* have lm_sensors 3.6.0 installed? (in another arch instance, collectd built fine. lm_sensors was not installed on the other instance)
* try to build collectd?

**Comment by igorpeshansky** [comment]
This is the fork of collectd used as the Google Cloud monitoring agent. Arch Linux is not supported by this agent. For the list of supported Linux distributions, see the [Google Cloud monitoring agent documentation](https://cloud.google.com/monitoring/agent#supported_operating_systems).
Did you mean to file this issue against the [main collectd repo](https://github.com/collectd/collectd)?
